[package]
name = "static_site_generator"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
pathdiff = "0.2.3"
regex = "1.11.2"
serde = { version = "1.0.225", features = ["derive"] }
serde_json = "1.0.145"
serde_yaml = "0.9.34"
